# vim: ft=yaml.docker-compose
---
name: trilium

include:
  - ext/docker-compose-snippets/tailscale-caddy.yaml
  - ext/docker-compose-snippets/simple-reverse-proxy.yaml
  - ext/docker-compose-snippets/volume-backup-schedules.yaml

services:
  trilium:
    image: ghcr.io/rahulsalvi/trilium:latest
    environment:
      TRILIUM_DATA_DIR: /home/node/trilium-data
      TRILIUM_NETWORK_HOST: 127.0.0.1
      TRILIUM_NETWORK_PORT: 8080
      TRILIUM_NETWORK_TRUSTEDREVERSEPROXY: loopback
    volumes:
      - trilium-data:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

  backup:
    volumes:
      - trilium-data:/backup:ro
    extends:
      file: ext/docker-compose-snippets/volume-backup.yaml
      service: aws-backup-frequent

volumes:
  trilium-data:
